"""create_initial_tables

Revision ID: dd40317f5f97
Revises: 
Create Date: 2025-06-24 15:53:00.347802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd40317f5f97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_badges_id'), 'badges', ['id'], unique=False)
    op.create_table('imagestyles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dalle_prompt_modifier', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_imagestyles_id'), 'imagestyles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.Enum('GOOGLE', 'MICROSOFT', name='userprovider_enum'), nullable=True),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_provider_id'), 'users', ['provider_id'], unique=True)
    op.create_table('dailymysteries',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('theme', sa.String(length=100), nullable=False),
    sa.Column('base_story_text', sa.Text(), nullable=False),
    sa.Column('actual_solution_text', sa.Text(), nullable=False),
    sa.Column('character_dossiers', sa.JSON(), nullable=True),
    sa.Column('critical_path_clues', sa.JSON(), nullable=True),
    sa.Column('image_style_id', sa.Integer(), nullable=False),
    sa.Column('base_image_urls', sa.JSON(), nullable=True),
    sa.Column('initial_choices_pool', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['image_style_id'], ['imagestyles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dailymysteries_date'), 'dailymysteries', ['date'], unique=True)
    op.create_index(op.f('ix_dailymysteries_id'), 'dailymysteries', ['id'], unique=False)
    op.create_table('userbadges',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'badge_id')
    )
    op.create_table('usermysterysessions',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('daily_mystery_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_solved', sa.Boolean(), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('path_taken', sa.JSON(), nullable=True),
    sa.Column('detective_rank', sa.String(length=50), nullable=True),
    sa.Column('final_video_url', sa.String(), nullable=True),
    sa.Column('collected_clues', sa.JSON(), nullable=True),
    sa.Column('notebook_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['daily_mystery_id'], ['dailymysteries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usermysterysessions_daily_mystery_id'), 'usermysterysessions', ['daily_mystery_id'], unique=False)
    op.create_index(op.f('ix_usermysterysessions_id'), 'usermysterysessions', ['id'], unique=False)
    op.create_index(op.f('ix_usermysterysessions_user_id'), 'usermysterysessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usermysterysessions_user_id'), table_name='usermysterysessions')
    op.drop_index(op.f('ix_usermysterysessions_id'), table_name='usermysterysessions')
    op.drop_index(op.f('ix_usermysterysessions_daily_mystery_id'), table_name='usermysterysessions')
    op.drop_table('usermysterysessions')
    op.drop_table('userbadges')
    op.drop_index(op.f('ix_dailymysteries_id'), table_name='dailymysteries')
    op.drop_index(op.f('ix_dailymysteries_date'), table_name='dailymysteries')
    op.drop_table('dailymysteries')
    op.drop_index(op.f('ix_users_provider_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_imagestyles_id'), table_name='imagestyles')
    op.drop_table('imagestyles')
    op.drop_index(op.f('ix_badges_id'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
